# Generated by Django 5.1.6 on 2025-02-21 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='career',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='career.level', verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='career',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='careers', to=settings.AUTH_USER_MODEL, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='career',
            name='short_name',
            field=models.CharField(max_length=10, verbose_name='Nombre corto'),
        ),
        migrations.AlterField(
            model_name='career',
            name='year',
            field=models.CharField(max_length=5, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='level',
            name='short_name',
            field=models.CharField(max_length=10, verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='career.career', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='career.quarter', verbose_name='Cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='weekly_hours',
            field=models.IntegerField(verbose_name='Horas por semana'),
        ),
    ]
